// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models
{
    public partial class Kvalifikacija
    {
        public Kvalifikacija()
        {
            Suradnik = new HashSet<Suradnik>();
        }

        public int IdKvalifikacija { get; set; }
        public string NazivKvalifikacija { get; set; }

        public virtual ICollection<Suradnik> Suradnik { get; set; }
    }
}