// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

public partial class Log
{
    public int Id { get; set; }

    public string MachineName { get; set; }

    public DateTime Logged { get; set; }

    public string Level { get; set; }

    public string Message { get; set; }

    public string Logger { get; set; }

    public string Properties { get; set; }

    public string Callsite { get; set; }

    public string Exception { get; set; }

    public string Url { get; set; }

    public string QueryString { get; set; }

    public string Action { get; set; }

    public string TraceId { get; set; }
}