// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models
{
    public partial class Partner
    {
        public Partner()
        {
            Suradniks = new HashSet<Suradnik>();
            IdProjekts = new HashSet<Projekt>();
        }

        public int IdPartner { get; set; }
        public string Oib { get; set; }
        public string AdresaPartner { get; set; }
        public string Ibanpartner { get; set; }
        public string EmailPartner { get; set; }
        public string NazivPartner { get; set; }
        public int IdTipPartnera { get; set; }

        public virtual TipPartnera IdTipPartneraNavigation { get; set; }
        public virtual ICollection<Suradnik> Suradniks { get; set; }

        public virtual ICollection<Projekt> IdProjekts { get; set; }
    }
}