// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models
{
    public partial class Posao
    {
        public Posao()
        {
            Oibs = new HashSet<Suradnik>();
        }

        public int IdPosao { get; set; }
        public int IdVrstaPosao { get; set; }

        public virtual VrstaPosla IdVrstaPosaoNavigation { get; set; }

        public virtual ICollection<Suradnik> Oibs { get; set; }
    }
}