// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace RPPP_WebApp.Models
{
    public partial class ProjektnaKartica
    {
        public ProjektnaKartica()
        {
            Transakcija = new HashSet<Transakcija>();
        }

        public double Saldo { get; set; }


        [Display(Name = "IBAN subjekta")]
        [Required(ErrorMessage = "Potrebno je napisati valjani IBAN")]
        [RegularExpression(@"^[A-Z]{2}\d{2}[A-Z0-9]{1,30}$", ErrorMessage = "Invalid IBAN format.")]
        public string SubjektIban { get; set; }

        [Display(Name = "Valuta")]
        [Required(ErrorMessage = "Potrebno je odabrati valutu")]
        public string Valuta { get; set; }


        [DataType(DataType.Date)]
        [Display(Name = "Datum")]
        [Required(ErrorMessage = "Potrebno je odabrati datum ")]
        public DateTime VrijemeOtvaranja { get; set; }


        [Display(Name = "Projekt")]
        [Required(ErrorMessage = "Potrebno je odabrati projekt")]
        public int IdProjekt { get; set; }


        public virtual Projekt IdProjektNavigation { get; set; }
        public virtual ICollection<Transakcija> Transakcija { get; set; }
    }
}