// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models
{
    public partial class Projekt
    {
        public Projekt()
        {
            Dokuments = new HashSet<Dokument>();
            ProjektnaKarticas = new HashSet<ProjektnaKartica>();
            Ulogas = new HashSet<Uloga>();
            Zahtjevs = new HashSet<Zahtjev>();
            IdPartners = new HashSet<Partner>();
        }

        public int IdProjekt { get; set; }
        public DateTime VrPocetak { get; set; }
        public DateTime? VrKraj { get; set; }
        public string Opis { get; set; }
        public string Naziv { get; set; }
        public int IdTip { get; set; }

        public virtual TipProjektum IdTipNavigation { get; set; }
        public virtual ICollection<Dokument> Dokuments { get; set; }
        public virtual ICollection<ProjektnaKartica> ProjektnaKarticas { get; set; }
        public virtual ICollection<Uloga> Ulogas { get; set; }
        public virtual ICollection<Zahtjev> Zahtjevs { get; set; }

        public virtual ICollection<Partner> IdPartners { get; set; }
    }
}