// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

public partial class Radi
{
    public string Oib { get; set; }

    public int IdPosao { get; set; }

    public int? IdSuradnik { get; set; }

    public virtual Posao IdPosaoNavigation { get; set; }

    public virtual Suradnik OibNavigation { get; set; }
}