// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace RPPP_WebApp.Models
{
    public partial class Suradnik
    {
        public Suradnik()
        {
            IdPosao = new HashSet<Posao>();
        }

        [Display(Name = "OIB")]
        [Required(ErrorMessage = "Potrebno je unjeti OIB")]
        [RegularExpression(@"^[0-9]{11}$", ErrorMessage = "OIB mora sadržavati točno 11 znamenki.")]
        [StringLength(11, ErrorMessage = "OIB mora imati točno 11 znakova.")]
        public string Oib { get; set; }

        [Display(Name = "Broj mobitela")]
        [Required(ErrorMessage = "Potrebno je unjeti broj mobitela")]
        [RegularExpression(@"^[0-9]+$", ErrorMessage = "Broj mobitela smije koristiti samo brojke")]
        public string Mobitel { get; set; }

        [Display(Name = "Ime")]
        [Required(ErrorMessage = "Potrebno je unjeti ime suradnika")]
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "Ime može imati samo slova.")]
        public string Ime { get; set; }

        [Display(Name = "Prezime")]
        [Required(ErrorMessage = "Potrebno je unjeti prezime suradnika")]
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "Prezime može imati samo slova.")]
        public string Prezime { get; set; }

        [Display(Name = "Email")]
        [Required(ErrorMessage = "Potrebno je unjeti Email adresu.")]
        [EmailAddress(ErrorMessage = "Email adresa nije validna.")]
        [RegularExpression(@"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$", ErrorMessage = "Email adresa nije validna.")]
        public string Mail { get; set; }
        public string Stranka { get; set; }
        public int IdSuradnik { get; set; }
        public int IdKvalifikacija { get; set; }
        public int IdPartner { get; set; }

        public virtual Kvalifikacija IdKvalifikacijaNavigation { get; set; }
        public virtual Partner IdPartnerNavigation { get; set; }

        public virtual ICollection<Posao> IdPosao { get; set; }
    }
}