// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models
{
    public partial class TipProjektum
    {
        public TipProjektum()
        {
            Projekts = new HashSet<Projekt>();
        }

        public int IdTip { get; set; }
        public string NazivTip { get; set; }

        public virtual ICollection<Projekt> Projekts { get; set; }
    }
}