// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models
{
    public partial class TipPartnera
    {
        public TipPartnera()
        {
            Partner = new HashSet<Partner>();
        }

        public int IdTipPartnera { get; set; }
        public string TipPartnera1 { get; set; }

        public virtual ICollection<Partner> Partner { get; set; }
    }
}