// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace RPPP_WebApp.Models
{
    public partial class Transakcija
    {


        [Display(Name = "Opis transakcije")]
        [Required(ErrorMessage = "Potrebno je napisati opis zahtjeva")]
        [StringLength(100, ErrorMessage = "Opis ima maksimalno 100 znakova.")]
        public string Opis { get; set; }


        [Display(Name = "IBAN primatelja")]
        [Required(ErrorMessage = "Potrebno je napisati valjani IBAN")]
        [RegularExpression(@"^[A-Z]{2}\d{2}[A-Z0-9]{1,30}$", ErrorMessage = "Invalid IBAN format.")]
        public string PrimateljIban { get; set; }


        [Display(Name = "Vrsta")]
        [Required(ErrorMessage = "Potrebno je odabrati vrstu")]
        public string Vrsta { get; set; }


        [Display(Name = "IBAN subjekta")]
        [Required(ErrorMessage = "Potrebno je napisati valjani IBAN")]
        [RegularExpression(@"^[A-Z]{2}\d{2}[A-Z0-9]{1,30}$", ErrorMessage = "Invalid IBAN format.")]
        public string SubjektIban { get; set; }


        [Display(Name = "IdTransakcije")]
        [Required(ErrorMessage = "Potrebno je odabrati transakciju")]
        public int IdTransakcije { get; set; }


        [Display(Name = "Vrijednost")]
        [Required(ErrorMessage = "Potrebno je odabrati vrijednost")]
        public int Vrijednost { get; set; }


        [Display(Name = "Valuta")]
        [Required(ErrorMessage = "Potrebno je odabrati valutu")]
        public string Valuta { get; set; }

        public virtual VrstaTransakcije IdTransakcijeNavigation { get; set; }
        public virtual ProjektnaKartica SubjektIbanNavigation { get; set; }
    }
}