// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models
{
    public partial class VrstaPosla
    {
        public VrstaPosla()
        {
            Posao = new HashSet<Posao>();
        }

        public int IdVrstaPosao { get; set; }
        public string NazivPosao { get; set; }

        public virtual ICollection<Posao> Posao { get; set; }
    }
}