// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models
{
    public partial class VrstaZahtjeva
    {
        public VrstaZahtjeva()
        {
            Zahtjev = new HashSet<Zahtjev>();
        }

        public int IdVrsta { get; set; }
        public string NazivVrsta { get; set; }

        public virtual ICollection<Zahtjev> Zahtjev { get; set; }
    }
}