// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models
{
    public partial class VrstaDokumentum
    {
        public VrstaDokumentum()
        {
            Dokuments = new HashSet<Dokument>();
        }

        public int IdVrstaDok { get; set; }
        public string NazivVrstaDok { get; set; }

        public virtual ICollection<Dokument> Dokuments { get; set; }
    }
}