// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace RPPP_WebApp.Models
{
    public partial class Zadatak
    {
        public DateTime? VrKraj { get; set; }
        public DateTime VrPoc { get; set; }
        public string Oibnositelj { get; set; }
        public int IdZadatak { get; set; }
        public string Vrsta { get; set; }
        public DateTime VrKrajOcekivano { get; set; }
        public int IdZahtjev { get; set; }
        public int IdStatus { get; set; }

        public virtual StatusZadatka IdStatusNavigation { get; set; }
        public virtual Zahtjev IdZahtjevNavigation { get; set; }
    }
}