// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models
{
    public partial class Zahtjev
    {
        public Zahtjev()
        {
            Zadatak = new HashSet<Zadatak>();
        }

        public string Opis { get; set; }
        public string Prioritet { get; set; }
        public int IdZahtjev { get; set; }
        public DateTime? VrKraj { get; set; }
        public DateTime VrKrajOcekivano { get; set; }
        public DateTime VrPocetak { get; set; }
        public int IdVrsta { get; set; }
        public int IdProjekt { get; set; }

        public virtual Projekt IdProjektNavigation { get; set; }
        public virtual VrstaZahtjeva IdVrstaNavigation { get; set; }
        public virtual ICollection<Zadatak> Zadatak { get; set; }
    }
}